CREATE SCHEMA BDAR;
SET SEARCH_PATH TO BDAR;

CREATE TABLE ACCOUNT(
   ID SERIAL PRIMARY KEY,
   USERNAME VARCHAR (50) UNIQUE NOT NULL,
   PASSWORD_HASH VARCHAR NOT NULL,
   FIRSTNAME VARCHAR(50) NOT NULL,
   LASTNAME VARCHAR(100) NOT NULL,
   EMAIL VARCHAR (355) UNIQUE NOT NULL,
   PHONE_NUMBER VARCHAR(15) UNIQUE NOT NULL,
   CREATED_ON TIMESTAMP NOT NULL,
   LAST_LOGIN TIMESTAMP
);

CREATE TABLE CREDIT_CARD(
   ID SERIAL PRIMARY KEY,
   CC VARCHAR UNIQUE NOT NULL,
   CC_NUM VARCHAR NOT NULL,
   HOLDER_NAME VARCHAR NOT NULL,
   EXPIRE_DATE TIMESTAMP NOT NULL,
   ACCOUNT_ID INTEGER REFERENCES ACCOUNT(ID)
);

CREATE TABLE PRODUCT(
   ID SERIAL PRIMARY KEY,
   PRODUCT_NAME VARCHAR(100) NOT NULL,
   PRODUCT_TYPE VARCHAR(20),
   DESCRIPTION VARCHAR(255),
   STOCK INTEGER NOT NULL,
   PRICE NUMERIC NOT NULL
);

CREATE TABLE REVIEW(
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INTEGER REFERENCES ACCOUNT(ID),
	PRODUCT_ID INTEGER REFERENCES PRODUCT(ID),
	MESSAGE VARCHAR(255),
	RATING INTEGER NOT NULL
);

CREATE TABLE PURCHASE_HISTORY(
	ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INTEGER REFERENCES ACCOUNT(ID),
	PRODUCT_ID INTEGER REFERENCES PRODUCT(ID),
	PURCHASE_DATE TIMESTAMP NOT NULL
);

CREATE TABLE ADDRESS(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	ADDRESS1 VARCHAR(100) NOT NULL,
	ADDRESS2 VARCHAR(100),
	CITY VARCHAR(100) NOT NULL,
	STATE_PROVINCE VARCHAR(100) NOT NULL,
	POSTAL_CODE VARCHAR(10) NOT NULL,
	ACCOUNT_ID INTEGER REFERENCES ACCOUNT(ID)
);



INSERT INTO ACCOUNT(USERNAME,PASSWORD_HASH,FIRSTNAME, LASTNAME,EMAIL,PHONE_NUMBER,CREATED_ON,LAST_LOGIN) VALUES 
('VARDENIS', MD5('PASSWORD'),'VARDENIS', 'PAVARDENIS' ,'VARDENIS.TEST@GMAIL.COM','+37000000000', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + (20 * INTERVAL '1 MINUTE'));

INSERT INTO ACCOUNT(USERNAME,PASSWORD_HASH,FIRSTNAME, LASTNAME,EMAIL,PHONE_NUMBER,CREATED_ON,LAST_LOGIN) VALUES 
('VARDELIS', MD5('PASSWORD'),'VARDELIS', 'PAVARDELIS' ,'VARDELIS.TEST@GMAIL.COM','+3701234567', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + (20 * INTERVAL '1 MINUTE'));

INSERT INTO ACCOUNT(USERNAME,PASSWORD_HASH,FIRSTNAME, LASTNAME,EMAIL,PHONE_NUMBER,CREATED_ON,LAST_LOGIN) VALUES 
('VARDAUSKAS', MD5('PASSWORD'),'VARDAUSKAS', 'PAVARDAUSKAS' ,'VARDAUSKAS.TEST@GMAIL.COM','+3709876652', CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + (20 * INTERVAL '1 MINUTE'));

INSERT INTO CREDIT_CARD(CC,CC_NUM,HOLDER_NAME,EXPIRE_DATE,ACCOUNT_ID) VALUES 
('1000 1234 5678 9010','111','VARDENIS PAVARDENIS', CURRENT_TIMESTAMP + (5 * INTERVAL '1 YEAR'),1);

INSERT INTO CREDIT_CARD(CC,CC_NUM,HOLDER_NAME,EXPIRE_DATE,ACCOUNT_ID) VALUES 
('1000 1234 5678 9011','112','VARDENIS PAVARDENIS', CURRENT_TIMESTAMP + (5 * INTERVAL '1 YEAR'),1);

INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_TYPE, DESCRIPTION, STOCK, PRICE) VALUES 
('SAMSUNG GALAXY 7', 'SMARTPHONE', 'GOOD, RELIABLE, BUT WEAK BATTERY', 1, 80);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_TYPE, DESCRIPTION, STOCK, PRICE) VALUES 
('SAMSUNG GALAXY 8', 'SMARTPHONE', 'BETTER THAN 7 , GOOD, RELIABLE, BUT WEAK BATTERY', 1, 180);
INSERT INTO PRODUCT(PRODUCT_NAME, PRODUCT_TYPE, DESCRIPTION, STOCK, PRICE) VALUES 
('SAMSUNG GALAXY 9', 'SMARTPHONE', 'BETTER THAN 8 , GOOD, RELIABLE, BUT WEAK BATTERY', 1, 380);

INSERT INTO REVIEW(ACCOUNT_ID, PRODUCT_ID,MESSAGE, RATING) VALUES 
(1, 2, 'I LIKED IT', 9);
INSERT INTO REVIEW(ACCOUNT_ID, PRODUCT_ID,MESSAGE, RATING) VALUES 
(1, 1, 'NOT SO GOOD. QUITE OLD', 7);

INSERT INTO PURCHASE_HISTORY(ACCOUNT_ID, PRODUCT_ID, PURCHASE_DATE) VALUES
(1,2, CURRENT_TIMESTAMP);
INSERT INTO PURCHASE_HISTORY(ACCOUNT_ID, PRODUCT_ID, PURCHASE_DATE) VALUES
(1,1, CURRENT_TIMESTAMP);


INSERT INTO ADDRESS(NAME, ADDRESS1, ADDRESS2, CITY ,STATE_PROVINCE, POSTAL_CODE, ACCOUNT_ID) VALUES 
('HOME', 'KONSTITUCIJOS 00-0', NULL, 'VILNIUS', 'VILNIAUS APSKRITIS', '45678', 1);
INSERT INTO ADDRESS(NAME, ADDRESS1, ADDRESS2, CITY ,STATE_PROVINCE, POSTAL_CODE, ACCOUNT_ID) VALUES 
('HOME', 'KONSTITUCIJOS 00-0', NULL, 'VILNIUS', 'VILNIAUS APSKRITIS', '44009', 2);
INSERT INTO ADDRESS(NAME, ADDRESS1, ADDRESS2, CITY ,STATE_PROVINCE, POSTAL_CODE, ACCOUNT_ID) VALUES 
('HOME', 'KONSTITUCIJOS 00-0', NULL, 'VILNIUS', 'VILNIAUS APSKRITIS', '46888', 3);

CREATE VIEW PERSONS_VIEW AS 
SELECT AA.ID, AA.FIRSTNAME, AA.LASTNAME, AA.EMAIL,AA.PHONE_NUMBER, AD."NAME",AD.ADDRESS1, AD.ADDRESS2, AD.CITY, AD.STATE_PROVINCE, AD.POSTAL_CODE FROM ACCOUNT AA
LEFT JOIN ADDRESS AD ON AD.ACCOUNT_ID = AA.ID;


SELECT * FROM ACCOUNT;
SELECT * FROM CREDIT_CARD;
SELECT * FROM PRODUCT;
SELECT * FROM REVIEW;
SELECT * FROM PURCHASE_HISTORY;
SELECT * FROM ADDRESS;
SELECT * FROM PERSONS_VIEW PV